### PR TITLE
Dump requests histogram + filter namespaces

### PR DESCRIPTION
**Pull request by caruccio**
This PR does two things:

1. Dump `requests` histogram based on suggestions from #64 
2. Add environment vars to include/exclude namespaces from accounting

### CODE REVIEW

**Comment by rchakode** [comment]
Look interesting, let me check that and give you feedback asap.

**Comment by rchakode** [comment]
@caruccio 
The code is failing on lint.

Please run `tox` from the source directory to check that the test and lint pass.
 => you may need to install tox (`sudo apt install tox`) and requirements.txt (`pip3 install -r requirements.txt`

**Comment by rchakode** [comment]
@caruccio 
I also suggest the following commits to add accounting charts for requests:
* 765ac7bcd5671ffc60f5dba0b1f3d8f8f9d1e10e
* 8fd0c51e1e135a020d1bd3b762bf8884840cccec
* 28155e62a680fe7be2c6c0905b32548a3225fe0f

Does that make sense for you?

R.

**Comment by rchakode** [comment]
@caruccio 
I have a problem : If I merge my branch, I will have conflict with your PR and may be required to close it (i.e. not merged) => Your commits will be preserved , but your PR will NOT be considered as "merged".

So can you just sherry-pick my changes on your branch so I can merge it?

Thanks.

**Comment by caruccio** [comment]
@rchakode just did a full merge. cherry pick was also conflicting on my side.

**Review by rchakode — APPROVED** [review]

**Pull request merged**
