### PR TITLE
Serviceaccount fix and prometheus operator support

### PR DESCRIPTION
**Pull request by volatilemolotov**
Added proper RBAC supoort using a serviceaccount just for this and binded to a clusterrole that has the minimum needed permissions. 

Added support to deploy a prometheus servicemonitor for those that use prometheus operator

### CODE REVIEW

**Comment by mumrau** [comment]
Oh it's quite funny, I was implementing the exact same features today!

I have additional support for statefulSet and better ways to handle pvcs, I'll wait till this get merged to push my changes as it would probably be hell to mix the 2 PRs.

**Comment by rchakode** [comment]
Hi, 
Dear @volatilemolotov, this PR is an awesome contribution. I'll review it and let you know.

@mumrau Nice to hear that things may be improved, please don't hesitate to submit your PR when this one will be merged.

R.

**Comment by volatilemolotov** [comment]
Haha, nice. Forgot to mention that I have removed the PVC class, this way it will deploy the default instead of throwing an error class not found

**Comment by rchakode** [comment]
Hi,
I was wondering why the storage class was removed, thanks for the explanation.

**Comment by rchakode** [comment]
Dear @volatilemolotov, 
The PR is merged, I also updated the README to highlight those changes.

Dear @mumrau,  thing you can get the latest changes in order to submit your PR concerning StatefulSet. 

Thanks again to all of you for your contributions.

**Pull request merged**
