### PR TITLE
Adding a helm chart

### LINKED ISSUE #8: Add option to ignore SSL validation
When running from within a kubernetes cluster we can use `https://kubernetes.default` for the API endpoint but the ssl cert will not be valid for that host name, resulting in:

```
2019-55-12 15:55:27 [ERROR] HTTP exception requesting 'https://kubernetes.default/api/v1/pods' (HTTPSConnectionPool(host='kubernetes.default', port=443): Max retries exceeded with url: /api/v1/pods (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),)))
2019-55-12 15:55:27 [ERROR] HTTP exception requesting 'https://kubernetes.default/apis/metrics.k8s.io/v1beta1/pods' (HTTPSConnectionPool(host='kubernetes.default', port=443): Max retries exceeded with url: /apis/metrics.k8s.io/v1beta1/pods (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),)))
```

so it would be nice to be able to skip ssl validation for this situation.

### PR DESCRIPTION
**Pull request by luisdavim**
This adds a helm chart and also fixes #8

### CODE REVIEW

**Comment by luisdavim** [comment]
my vim is configured to automatically remove tailing white spaces so you'll see some white space changes...

**Comment by rchakode** [comment]
Hi,
Very pleased to receive these interesting contributions.
As a first and quick review, it seems to miss documentation to use the helm chart. 
Can you consider to add a short paragraph in the README for such a purpose please?

**Comment by luisdavim** [comment]
Sure, I'll update the PR.

**Comment by rchakode** [comment]
Thanks, I'll test it and let you know.

**Comment by rchakode** [comment]
Enhancements are merged with few fixes and docs updates:
* fixed repository in  values.yaml removing ":latest" at the end
* environments variables should be quoted, otherwise the deployment will fail on certain versions of k8s 
* externalizing storage capacity config
* ...

You can find more details in my latest commit

**Pull request closed without merging**
